### ISSUE TITLE
Spawn everywhere?

### ISSUE THREAD

**Issue by GTPManager** [BambooPM/MobsLite#6]
You should make, like an option
spawnInEveryWorld: true(or false)
With blacklisted worlds
Like
#use this option if you set spawn in every world to true
#write world names where u dont want mobs spawning
Blacklisted:
- "SkyHub"

**Comment by pandaa-be** [comment]
This would cause laggs, it is already to much to have 3 different worlds 😵‍💫

Fell free to edit the code yourself if you need this feature.

**Comment by GTPManager** [comment]
> This would cause laggs, it is already to much to have 3 different worlds 😵‍💫
> 
> Fell free to edit the code yourself if you need this feature.
> 
> (Edit: Your idea would not work, there are 3 different type of mobs - Overworld, Nether and End Mobs)

It would lag if you have a trashy server, everyone needs this feature, it would work, i thought you would understand that am only talking about overworld mobs, PHP is very light, that wouldn't lag, only if the server is trash.

**Comment by GTPManager** [comment]
Reopened

**Comment by GTPManager** [comment]
I would if i could code on a mobile phone =-=

**Comment by GTPManager** [comment]
Plus, mobs don't spawn if its not rendered, unless u bypassed that, Multiworld, loads or unloads the worlds, if the world doesn't have any players, it gets unload (un-render chunks) + anti-lag exist which clears the mobs if there is too much

**Comment by GTPManager** [comment]
It was just a suggestion, your choise mate, have a good day

**Comment by GTPManager** [comment]
Owner won't add such feature ig

**Comment by pandaa-be** [comment]
> Owner won't add such feature ig (closed)

It doesn't make sense to me, I've had the plugin running on my server for several months and I'll probably know what the performance is like.

Test server: 4 cores and 8GB RAM

I won't add the feature for now, the plugin was developed for my server and it's only open source so others can use it as a base.

It has not been my goal to add features that I don't need....

**Comment by GTPManager** [comment]
Okay
